### ISSUE TITLE
process.argv[1] is undefined when ENVIRONMENT_IS_NODE

### ISSUE THREAD

**Issue by fritx** [yxl/opencore-amr-js#2]
Using this lib in [nw.js](https://github.com/nwjs/nw.js) where it is node env but the `process.argv[1]` is undefined, causing an Error:

```plain
Uncaught TypeError: Cannot read property 'replace' of undefined
```

```js
// hack to fix bug and it works
// Module["thisProgram"] = process["argv"][1].replace(/\\/g, "/");
Module["thisProgram"] = process["argv"][1] && process["argv"][1].replace(/\\/g, "/");
```

Any idea? Thanks!

**Comment by yxl** [comment]
It is a bug of the emscripten of an early version and rebuilding the js library with the latest emscripten fixes this.

**Comment by fritx** [comment]
nice
