### ISSUE TITLE
Should have only one AudioContext per page

### ISSUE THREAD

**Issue by fritx** [yxl/opencore-amr-js#3]
```plain
Failed to construct 'AudioContext': number of hardware contexts reached maximum (6)
```

see: http://stackoverflow.com/a/25046735/3855809

https://github.com/yxl/opencore-amr-js/blob/master/js%2Fdemo.html#L132

`var ctx = new AudioContext();` should be moved to outer scope to keep

**Comment by yxl** [comment]
@fritx Thanks. It has been fixed.

**Comment by fritx** [comment]
nice

**Comment by fritx** [comment]
by the way, why does it require chrome 39+?

**Comment by yxl** [comment]
It may work on an older browser, but I haven't test that. 

The AMR encoder and decoder should be compatible with more versions of chrome browser. 

But a few new APIs, such as `AudioContext` and `TextEncoder` are only available with the recent versions.
